### ISSUE TITLE
Feedback on code generation in register example in README

### ISSUE THREAD

**Issue by slightknack** [FastVM/minivm#7] opened 2022-01-08 17:53 UTC
Doug Currie sent me the following in an email: I think it's a really useful bit of advice, and I hope he doesn't mind if I put what he wrote here so others can see it. Thanks for taking the time to write an email and point this out, I really appreciate it!

> The example
> ```
> // r0 is where x lives
> head_of_loop:
>   jump_if_reg_less_than_number r0 1000 :end_of_loop
>   increment_reg r0 1
>   jump :head_of_loop
> end_of_loop:
> ```
> certainly shows the advantage of register VM over stack VM, but hopefully a code generator would emit
> ```
> // r0 is where x lives
>   jump :test_of_loop
> head_of_loop:
>   increment_reg r0 1
>   jump_if_reg_NOT_less_than_number r0 1000 :head_of_loop
> end_of_loop:
> ```
> which reduces the loop instruction count from three to two ops. Of course the same optimization is possible in the stack based VM, but it’s a bit more complicated.

Although I do *some* VM engineering, I'm not the author of MiniVM (just wrote most of the README), so I'd love to see what @ShawSumma's thoughts on this are. I'll probably include the shorter version in the README when I do a round of edits later this week.

cc: @dcurrie

**Comment by ShawSumma** [comment] 2022-01-08 18:09
MiniVM does no optimization yet. What code is generated is run!

This is one example of branch optimization.
What MiniVM could easily do is inline branches and constant fold a few times.

This allows for automatic loop unrolling. I need to write a MiniVM optimizer.

**Comment by ShawSumma** [comment] 2022-01-08 18:12
I appreciate your interest in MiniVM, it is very kind! It's been months of
work and I'm glad it finally is getting recognized. I posted a bit on
github about it, in the issue isaac linked.

**Comment by ShawSumma** [comment] 2024-05-13 11:55
MiniVM no longer uses this synax, so its not really relevant.

I'll close this for now.

**Closed by ShawSumma** 2024-05-13 11:55 UTC
